### ISSUE TITLE
Crashes on 1.15.1 forge 30.0.27+

### ISSUE THREAD

**Issue by Seegras** [KnightMiner/AnimalCrops#5]
Thread: Render thread
Stacktrace:
        at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
        at knightminer.animalcrops.client.ClientEvents.registerBlockColors(ClientEvents.java:49)
        at net.minecraftforge.eventbus.ASMEventHandler_27_ClientEvents_registerBlockColors_Block.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
        at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
        at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
        at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:203)
        at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

Same error, by the way, for simply tea.

**Comment by KnightMiner** [comment]
When posting crashes, you should post the full crash report, you missed 90% of the information. For this specific issue though, your full gamelog will be a lot more useful. Use a site such as gist.github.com or pastebin and link it here

**Comment by KrokoIsCoolne** [comment]
try to update Titanium when you use it

**Comment by KnightMiner** [comment]
Closing for lack of response
